An initial attempt to use nvrtc library for runtime cuda compilation
see #169

This mostly works, but fails some tests.

* It looks like the compiler backend (or compiler settings) that is used in
  nvrtc is a bit different from the one in nvcc. Some kernels that nvcc
  compiles just fine are not accepted by nvrtc.

  The notable example is the use of anonymous structs in shared union (used in
  sort algorithms):

      union Shared
      {
        struct
        {
          int keys0[3072];
        };
        struct
        {
          float vals0[2816];
        };
      };
      __shared__ union Shared shared;

  This results in the following compilation error when compiled with nvrtc:
      warning: declaration does not declare anything
      error: union "Shared" has no member "keys0"

* The compilation of FFT tests just seems to hang.

* And the caching does not work either with nvrtc, meaning that subsequent
  compiles take as much time as the first one.